use weed::core::{classify_file, FileKind, Lang};

#[test]
fn classifies_v1_languages_tests_manifests_guardrails_and_generated_files() {
    assert_eq!(classify_file("src/app.ts", "").lang, Lang::TypeScript);
    assert_eq!(classify_file("src/app.js", "").lang, Lang::JavaScript);
    assert_eq!(classify_file("pkg/tool.py", "").lang, Lang::Python);
    assert_eq!(classify_file("src/lib.rs", "").lang, Lang::Rust);
    assert_eq!(classify_file("cmd/main.go", "").lang, Lang::Go);

    assert_eq!(classify_file("src/app.test.ts", "").kind, FileKind::Test);
    assert_eq!(classify_file("tests/core_test.py", "").kind, FileKind::Test);
    assert_eq!(classify_file("pkg/foo_test.go", "").kind, FileKind::Test);
    assert_eq!(
        classify_file("src/lib.rs", "#[cfg(test)] mod tests {}").kind,
        FileKind::Test
    );

    for path in [
        "package.json",
        "Cargo.toml",
        "Cargo.lock",
        "pyproject.toml",
        "go.mod",
        "go.sum",
        "pnpm-lock.yaml",
        "package-lock.json",
        "poetry.lock",
    ] {
        assert_eq!(classify_file(path, "").kind, FileKind::Manifest, "{path}");
    }

    for path in [
        ".github/workflows/ci.yml",
        ".claude/settings.local.json",
        ".gemini/settings.json",
        ".codex/config.toml",
        "weed.toml",
        ".githooks/pre-commit",
        "AGENTS.md",
        "CLAUDE.md",
    ] {
        assert_eq!(classify_file(path, "").kind, FileKind::Guardrail, "{path}");
    }

    assert_eq!(classify_file("dist/app.js", "").kind, FileKind::Generated);
    assert_eq!(
        classify_file("src/vendor.min.js", "").kind,
        FileKind::Generated
    );
    assert_eq!(
        classify_file("src/generated.py", "# Generated by schema tool\nx = 1").kind,
        FileKind::Generated
    );
    assert_eq!(classify_file("README.md", "").kind, FileKind::Other);
    assert_eq!(classify_file("notes/thing.unknown", "").lang, Lang::Other);
}
