#!/usr/bin/env bash
# Evidence for calibration-audit.tend2.html: the audit files must declare
# whether they were blind, and the blind audit must rest on a packet that can be
# regenerated byte for byte from the pinned corpus.
set -euo pipefail

python3 - <<'PY'
import hashlib
import os
import pathlib
import re
import subprocess
import tempfile
import sys

REPORT = "docs/calibration-2026-09.md"
SIGHTED = "docs/calibration-audit-2026-09.md"
BLIND = "docs/calibration-audit-blind-2026-09.md"

CLASSIFICATIONS = {
    "true positive": "true-positive",
    "true-positive": "true-positive",
    "acceptable": "acceptable",
    "false positive": "false-positive",
    "false-positive": "false-positive",
}

complaints = []


def read(path):
    try:
        with open(path, encoding="utf-8") as handle:
            return handle.read()
    except FileNotFoundError:
        complaints.append(f"{path} is missing")
        return ""


def cell_text(cell):
    return re.sub(r"`([^`]*)`", r"\1", cell.strip()).strip()


def verdict(cell):
    text = cell_text(cell).lower()
    return CLASSIFICATIONS.get(text, text)


def table_cells(line):
    line = line.strip()
    if not line.startswith("|"):
        return None
    cells = [cell.strip() for cell in line.strip("|").split("|")]
    if all(re.fullmatch(r":?-{3,}:?", cell.replace(" ", "")) for cell in cells):
        return None
    return cells


def seeded_sample(items, seed, label, count=20):
    return sorted(
        items,
        key=lambda item: hashlib.sha256(
            f"{seed}\0{label}\0{item['key']}".encode("utf-8")
        ).hexdigest(),
    )[:count]


def parse_report(report):
    blocked = []
    repo = None
    in_recall = False
    for line in report.splitlines():
        if line.strip() == "<!-- recall:begin -->":
            in_recall = True
        if in_recall:
            continue
        heading = re.match(r"^##\s+([A-Za-z0-9_-]+),\s+\d+ commits judged,", line)
        if heading:
            repo = heading.group(1)
            continue
        cells = table_cells(line)
        if not repo or not cells or len(cells) < 4:
            continue
        commit_match = re.match(r"`?([0-9a-f]{9,40})`?\s+(.*)", cells[0])
        if not commit_match:
            continue
        original = verdict(cells[2])
        if original not in CLASSIFICATIONS.values():
            continue
        sha = commit_match.group(1)
        blocked.append(
            {
                "key": f"{repo}:{sha}",
                "repo": repo,
                "sha": sha,
                "original": original,
            }
        )

    recall = []
    recall_section = re.search(
        r"### Every miss\n\n(.*?)(?:\n### |\n<!-- recall:end -->)", report, re.S
    )
    if recall_section:
        for line in recall_section.group(1).splitlines():
            match = re.match(
                r"^- ([A-Z][0-9]) · ([a-z]+) · ([A-Za-z0-9_-]+) `([0-9a-f]{9,40})` · `([^`]+)`, (.+)$",
                line.strip(),
            )
            if not match:
                continue
            rule, lang, repo_name, sha, path, reason = match.groups()
            recall.append(
                {
                    "key": f"{rule}:{lang}:{repo_name}:{sha}:{path}",
                    "rule": rule,
                    "lang": lang,
                    "repo": repo_name,
                    "sha": sha,
                    "path": path,
                    "original": "miss",
                    "reason": reason,
                }
            )
    else:
        complaints.append(f"{REPORT} carries no recall miss list to sample")
    return blocked, recall


def parse_audit(path, audit):
    provider_match = re.search(r"(?im)^provider:\s*(.+?)\s*$", audit)
    if not provider_match or not provider_match.group(1).strip():
        complaints.append(f"{path} does not name the provider that produced it")

    blind_match = re.search(r"(?im)^blind:\s*(.+?)\s*$", audit)
    blind = blind_match.group(1).strip().lower() if blind_match else ""
    if not blind:
        complaints.append(f"{path} does not declare whether the auditor was blind")

    seed_match = re.search(r"(?im)^seed:\s*([A-Za-z0-9._:-]+)\s*$", audit)
    seed = seed_match.group(1) if seed_match else ""
    if not seed:
        complaints.append(f"{path} does not record a seeded shuffle")

    blocked_audit = {}
    recall_audit = {}
    agreement_rows = {}
    section = None
    for line in audit.splitlines():
        lowered = line.strip().lower()
        if lowered.startswith("## "):
            if "blocked commit" in lowered:
                section = "blocked"
            elif "recall case" in lowered:
                section = "recall"
            elif "agreement" in lowered:
                section = "agreement"
            else:
                section = None
            continue
        cells = table_cells(line)
        if not cells:
            continue
        header = [cell.lower() for cell in cells]
        if "repo" in header or "sample" in header or "rule" in header:
            continue
        if section == "blocked" and len(cells) >= 4:
            repo_name = cell_text(cells[0])
            sha = cell_text(cells[1])
            blocked_audit[f"{repo_name}:{sha}"] = {
                "verdict": verdict(cells[2]),
                "reason": cell_text(cells[3]),
            }
        elif section == "recall" and len(cells) >= 7:
            rule = cell_text(cells[0])
            lang = cell_text(cells[1])
            repo_name = cell_text(cells[2])
            sha = cell_text(cells[3])
            path_name = cell_text(cells[4])
            recall_audit[f"{rule}:{lang}:{repo_name}:{sha}:{path_name}"] = {
                "verdict": verdict(cells[5]),
                "reason": cell_text(cells[6]),
            }
        elif section == "agreement" and len(cells) >= 3:
            try:
                agreement_rows[cell_text(cells[0]).lower()] = (int(cells[1]), int(cells[2]))
            except ValueError:
                pass
    return {
        "path": path,
        "seed": seed,
        "blind": blind,
        "blocked": blocked_audit,
        "recall": recall_audit,
        "agreement": agreement_rows,
    }


def has_reason(row):
    reason = row.get("reason", "").strip()
    return len(reason) >= 20 and re.search(r"[A-Za-z]", reason)


def check_sample(audit, name, sample, audit_rows):
    agreed = 0
    for item in sample:
        row = audit_rows.get(item["key"])
        if row is None:
            complaints.append(f"{audit['path']} omits sampled {name} case {item['key']}")
            continue
        if not has_reason(row):
            complaints.append(f"{audit['path']} gives sampled {name} case {item['key']} no reasoning")
        if row["verdict"] == item["original"]:
            agreed += 1
    return len(sample), agreed


def check_audit(audit, blocked, recall):
    blocked_sample = seeded_sample(blocked, audit["seed"], "blocked") if audit["seed"] else []
    recall_sample = seeded_sample(recall, audit["seed"], "recall") if audit["seed"] else []
    blocked_count, blocked_agreed = check_sample(
        audit, "blocked", blocked_sample, audit["blocked"]
    )
    recall_count, recall_agreed = check_sample(audit, "recall", recall_sample, audit["recall"])

    expected_rows = {
        "blocked commits": (blocked_count, blocked_agreed),
        "recall cases": (recall_count, recall_agreed),
    }
    for sample_name, expected in expected_rows.items():
        actual = audit["agreement"].get(sample_name)
        if actual != expected:
            complaints.append(
                f"{audit['path']} agreement row for {sample_name} is {actual}, expected {expected}"
            )
        count, agreed = expected
        if count < 20:
            complaints.append(f"{audit['path']} {sample_name} sample has {count} cases; twenty are required")

    extra_blocked = set(audit["blocked"]) - {item["key"] for item in blocked_sample}
    extra_recall = set(audit["recall"]) - {item["key"] for item in recall_sample}
    if extra_blocked:
        complaints.append(f"{audit['path']} carries blocked rows outside the seeded sample")
    if extra_recall:
        complaints.append(f"{audit['path']} carries recall rows outside the seeded sample")
    return expected_rows


report = read(REPORT)
blocked, recall = parse_report(report)
if len(blocked) < 20:
    complaints.append(f"{REPORT} names only {len(blocked)} blocked commits; twenty are required")
if len(recall) < 20:
    complaints.append(f"{REPORT} names only {len(recall)} recall cases; twenty are required")

sighted = parse_audit(SIGHTED, read(SIGHTED))
blind = parse_audit(BLIND, read(BLIND))

if not sighted["blind"].startswith("no"):
    complaints.append(f"{SIGHTED} must declare `Blind: no` and what the auditor saw")
if "classification" not in sighted["blind"] and "class" not in sighted["blind"]:
    complaints.append(f"{SIGHTED} does not say what classification information the auditor could read")
if blind["blind"] != "yes":
    complaints.append(f"{BLIND} must declare `Blind: yes`")

sighted_rows = check_audit(sighted, blocked, recall)
blind_rows = check_audit(blind, blocked, recall)

# The blind audit is one packet per sampled case, written by code from the
# pinned corpus. Every case file in the tree has to be what the generator writes
# for the audit's seed today, byte for byte, and none may carry the ledger.
case_dir = pathlib.Path("fixtures/adversarial/calibration-audit/blind-2026-09/cases")
kept_cases = sorted(case_dir.glob("*.md")) if case_dir.is_dir() else []
if not kept_cases:
    complaints.append(f"{case_dir} carries no case packets")
else:
    with tempfile.TemporaryDirectory() as tmp:
        fresh_dir = pathlib.Path(tmp) / "cases"
        expected = subprocess.run(
            ["cargo", "xtask", "audit-packet", "--seed", blind["seed"], "--dir", str(fresh_dir)],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if expected.returncode != 0:
            complaints.append(
                "cargo xtask audit-packet --dir could not regenerate the case packets: "
                + expected.stderr.strip()
            )
        else:
            fresh_cases = sorted(fresh_dir.glob("*.md"))
            if [path.name for path in kept_cases] != [path.name for path in fresh_cases]:
                complaints.append(f"{case_dir} names differ from the packets regenerated for seed {blind['seed']}")
            for kept_path, fresh_path in zip(kept_cases, fresh_cases):
                kept_text = kept_path.read_text(encoding="utf-8")
                if kept_text != fresh_path.read_text(encoding="utf-8"):
                    complaints.append(f"{kept_path} differs from a freshly regenerated packet")
                if "builder's classification" in kept_text.lower():
                    complaints.append(f"{kept_path} names the builder's classification")
                if "## blocked commit sample" in kept_text.lower() or "## recall case sample" in kept_text.lower():
                    complaints.append(f"{kept_path} appears to contain an auditor response")

prose = "\n".join(
    line for line in report.splitlines() if line.strip() and not line.lstrip().startswith("#")
).strip()
first_sentence = re.split(r"(?<=[.!?])\s+", prose, maxsplit=1)[0] if prose else ""
all_rows = list(sighted_rows.values()) + list(blind_rows.values())
if any(agreed * 100 < 90 * count for count, agreed in all_rows):
    if "untrusted" not in first_sentence.lower():
        complaints.append(f"{REPORT}'s first sentence does not say the classification is untrusted")

if complaints:
    for complaint in complaints:
        print(complaint, file=sys.stderr)
    sys.exit(1)

print(
    f"calibration audit agreement stands: sighted blocked {sighted_rows['blocked commits'][1]}/{sighted_rows['blocked commits'][0]}, "
    f"sighted recall {sighted_rows['recall cases'][1]}/{sighted_rows['recall cases'][0]}, "
    f"blind blocked {blind_rows['blocked commits'][1]}/{blind_rows['blocked commits'][0]}, "
    f"blind recall {blind_rows['recall cases'][1]}/{blind_rows['recall cases'][0]}"
)
PY
