use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FileKind {
    Test,
    Prod,
    Config,
    Manifest,
    Generated,
    Guardrail,
    Other,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Lang {
    TypeScript,
    JavaScript,
    Python,
    Rust,
    Go,
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Classification {
    pub kind: FileKind,
    pub lang: Lang,
    /// A production file that also carries an inline test module (`#[cfg(test)]`
    /// in Rust). The file stays `Prod`; rules that count or read tests look here.
    pub has_inline_tests: bool,
}

pub fn classify_file(path: impl AsRef<Path>, content: &str) -> Classification {
    let path = path.as_ref();
    let path_text = normalize(path);
    let lang = classify_lang(path);
    let kind = if is_guardrail(&path_text) {
        FileKind::Guardrail
    } else if is_manifest(&path_text) {
        FileKind::Manifest
    } else if is_generated(&path_text, content) {
        FileKind::Generated
    } else if is_config(&path_text) {
        FileKind::Config
    } else if is_test(path, &path_text, lang) {
        FileKind::Test
    } else if lang != Lang::Other {
        FileKind::Prod
    } else {
        FileKind::Other
    };
    let has_inline_tests = kind == FileKind::Prod
        && lang == Lang::Rust
        && (content.contains("#[cfg(test)]") || content.contains("#[test]"));

    Classification {
        kind,
        lang,
        has_inline_tests,
    }
}

fn normalize(path: &Path) -> String {
    path.components()
        .collect::<PathBuf>()
        .to_string_lossy()
        .replace('\\', "/")
}

fn classify_lang(path: &Path) -> Lang {
    match path
        .extension()
        .and_then(|ext| ext.to_str())
        .unwrap_or_default()
    {
        "ts" | "tsx" => Lang::TypeScript,
        "js" | "jsx" | "mjs" | "cjs" => Lang::JavaScript,
        "py" => Lang::Python,
        "rs" => Lang::Rust,
        "go" => Lang::Go,
        _ => Lang::Other,
    }
}

fn is_guardrail(path: &str) -> bool {
    path == "weed.toml"
        || path == "AGENTS.md"
        || path == "CLAUDE.md"
        || path.starts_with(".github/workflows/")
        || path.starts_with(".codex/")
        || path.starts_with(".githooks/")
        || path == ".gemini/settings.json"
        || (path.starts_with(".claude/settings") && path.ends_with(".json"))
}

fn is_manifest(path: &str) -> bool {
    matches!(
        path.rsplit('/').next().unwrap_or(path),
        "package.json"
            | "Cargo.toml"
            | "Cargo.lock"
            | "pyproject.toml"
            | "requirements.txt"
            | "requirements-dev.txt"
            | "go.mod"
            | "go.sum"
            | "pnpm-lock.yaml"
            | "package-lock.json"
            | "yarn.lock"
            | "poetry.lock"
    )
}

fn is_generated(path: &str, content: &str) -> bool {
    let name = path.rsplit('/').next().unwrap_or(path);
    name.ends_with(".min.js")
        || name.ends_with(".min.css")
        || path.starts_with("dist/")
        || path.contains("/dist/")
        || path.starts_with("build/")
        || path.contains("/build/")
        || content.lines().take(5).any(|line| {
            let lower = line.to_ascii_lowercase();
            lower.contains("generated by")
                || lower.contains("auto-generated")
                || lower.contains("autogenerated")
                || lower.contains("do not edit")
        })
}

fn is_config(path: &str) -> bool {
    let name = path.rsplit('/').next().unwrap_or(path);
    path.starts_with(".github/")
        || matches!(
            name,
            "tsconfig.json"
                | "vite.config.ts"
                | "vite.config.js"
                | "jest.config.js"
                | "vitest.config.ts"
                | "pytest.ini"
                | "ruff.toml"
                | ".prettierrc"
                | ".eslintrc"
                | ".eslintrc.json"
                | ".gitignore"
        )
}

fn is_test(path: &Path, path_text: &str, lang: Lang) -> bool {
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default();
    path_text.contains("/tests/")
        || path_text.starts_with("tests/")
        || path_text.contains("/__tests__/")
        || name.contains(".test.")
        || name.contains(".spec.")
        || (lang == Lang::Python && (name.starts_with("test_") || name.ends_with("_test.py")))
        || (lang == Lang::Go && name.ends_with("_test.go"))
        || (lang == Lang::Rust
            && (path_text.starts_with("benches/")
                || path_text.contains("/benches/")
                || name.ends_with("_test.rs")
                || name == "tests.rs"))
}
